version: '3.4'

services:
  rabbitmq:
    container_name: rabbitmq
    image: "rabbitmq:3.9-management"
    labels:
      quarkus-dev-service-rabbitmq: rabbitmq
    ports:
      - 5671:5671
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q is_running"]
      interval: 20s
      timeout: 1s
      retries: 2
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /